version: "3"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment: 
        - DEMO_APP_ADDR=:8000
        - DEMO_REDIS_ADDR=redis:6379
    volumes:
      - logvolume01:/var/log
    depends_on: 
        - redis

  redis:
    image: redis:alpine
    container_name: redis_container
    ports:
        - "6379:6379"
    volumes: 
        - ../data/redis:/data
volumes: 
    logvolume01: {}
